### ISSUE TITLE
Can you provide psp-gcc compatible with gitpod ?

### ISSUE THREAD

**Issue by Mitchbux** [pspdev/gcc#1]
Hey ,

Can you provide psp-gcc compatible with gitpod ?

::/ https://gitpod.io /::

Thanks

**Comment by sharkwouter** [comment]
What would that require us to do? I've not heard of gitpod before, what does it do?

**Comment by Mitchbux** [comment]
gitpod.io is Visual Studio Code - like IDE for the web.
The codename is Theia. It has several docker images where the ide is ran from.
It can downloand, compile and execute directly from github.com repositories.
Nontheless, it doe not have sudo (su) like features. It also cannot apt-get.
Otherwise, you can download with wget : tarballs, compressed archive etc...
Then extract them to compile the toolchain.

Available commands : bash,awk,  gcc ,make ld etc.. for the x86_64 Linux platform.

Feel free to test it with a dummy account #)

**Comment by carstene1ns** [comment]
It looks to me like you do not want to work *on* the toolchain, but *with* the toolchain.

Should be enough to create the `.gitpod.yml` file for your project and reference our `Dockerfile` from there.
Might be worth to add some example project from the pspsdk to make this easier.
