### ISSUE TITLE
Broken C++ support in prx modules

### ISSUE THREAD

**Issue by Crow-bar** [pspdev/gcc#5]
libstdc++ uses $gp

The -mno-gpopt flag for target libraries(and also newlib) should solve this problem.

**Comment by diamant3** [comment]
Thanks for submitting an issue! If you don't mind creating a PR, you can refer to the https://github.com/pspdev/psptoolchain-allegrex repo to discuss more about that. All the scripts used to build the gcc compiler, newlib, and others are there, inside the `scripts` directory.

**Comment by bucanero** [comment]
Ref. https://github.com/pspdev/psptoolchain-allegrex/issues/24
